spring.application.name=disaster-relief

# 1. Database URL (muhafiz_db is your database)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=muhafiz_db;encrypt=true;trustServerCertificate=true
# 2. Database Credentials
spring.datasource.username=ammar
spring.datasource.password=ammar

# 3. Hibernate Configuration
# We set this to 'none' because you don't want to create tables yet.
# It will only check if the connection is successful.
spring.jpa.hibernate.ddl-auto=update


# 4. Driver and Dialect
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# 5. Logging (To see if it connects)
spring.jpa.show-sql=true

drms.jwt.secret=TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V
drms.jwt.expirationMs=86400000